### ISSUE TITLE
Making changes to config reverts back to old config

### ISSUE THREAD

**Issue by British89** [codetaylor/kor-noplace#1]
Hello, 

Been having problems adding items to the config, I beleive i am doing it right but the changes i make seem to break the mod, here is what i am doing. I beleive this is right? Place a new block within the "blocks" brackets? but for some reason if i have more than 1 block in this config file it reverts back to the default stone.

```json
 {
   "blocks": {
     "minecraft:stone:0": {
       "dimensionIdWhiteList": [],
        "dimensionIdBlackList": [
         0
       ],
       "returnedItem": "minecraft:stone:0",
       "message": "This is a test."
     }
     "minecraft:sand:0": {
       "dimensionIdWhiteList": [],
       "dimensionIdBlackList": [
         0
       ],
       "returnedItem": "minecraft:sand:0",
       "message": "This is also a test."
     }
   }
}
```

**Comment by codetaylor** [comment]
It looks like a comma is missing in the json you provided.

There should be a comma at the end of the line directly before the line that reads `"minecraft:sand:0": {`.

I was able to reproduce the behavior that you described with the missing comma. When the missing comma was added, everything worked as intended.

Hope this helps! :)

**Comment by British89** [comment]
It still is not working, Why am i having such problems with this, It's like i have never edited a config before.
Is it possible that you could give me an example config with 2 different blocks within it please?

Also not sure if you are done with this mod yet or not but if you are open to suggestions, Ingame commands to add blocks or a command to reload the config would be neat :P

Also i intended this to work with torches so they can not be placed, trying to make myself a RF pack with powered lights only, i assume torches are classed as items and not blocks? is there a way around this?

EDIT: Never mind it's sorted, i was editing the wrong instance of the file, Thanks for the help :)
